hugo:
    image: publysher/hugo
    command: hugo
    volumes:
        - .:/usr/share/blog

caddy:
    image: abiosoft/caddy
    restart: always
    volumes:
        - ./public:/srv
    ports:
        - 80:2015